### PR TITLE
Update ordered-set and ordered-map hash for Clojure 1.6.0

### PR DESCRIPTION
**Pull request by jafingerhut**

### CODE REVIEW

**Comment by amalloy** [comment]
Doesn't this compile-if joke mean that AOTed jars will be locked to the particular version of clojure they were compiled against? Like clojure.core.reducers had the same problem in a 1.5 alpha, as I recall, before they fixed it.

**Comment by jafingerhut** [comment]
I suppose it does.  The data.avl library is using this approach now, which is not to say that it is necessarily a good idea.

Would you prefer an approach that did the resolve once the first time hash was called, and cached the result somehow, so resolve did not need to be done on every call to hash?

**Comment by amalloy** [comment]
The easy way is to just `(def hasher (delay (if (resolve ...) (fn [x] ...) (fn [x] ...))))`, and then later you can just call `(@hasher this)`.

**Comment by amalloy** [comment]
Oh, but I guess that's a bit more complicated if you need to work with methods instead of just functions, because one of the paths has to call a method that doesn't exist. Any clever ideas to patch up my offhand suggestion into something that actually works?

**Pull request merged**
